### ISSUE TITLE
可以自定义form-item的label吗？  在文档上没看到这个选项

### ISSUE THREAD

**Issue by Ya-hui** [jjxliu306/ng-form-element#10]
比如我想label后面显示个info 提示鼠标移入到上面显示一些东西。可以支持吗

**Comment by jjxliu306** [comment]
这个思路可以，我在下个版本在form-item的label上加个插槽。到时候自定义嵌入代码
















在 2023-05-14 19:25:20，"Wy.H" ***@***.***> 写道：

比如我想label后面显示个info 提示鼠标移入到上面显示一些东西。可以支持吗

**Comment by jjxliu306** [comment]
现在已经支持动态label了
