### ISSUE TITLE
打包时，报错找不到Vue

### ISSUE THREAD

**Issue by tutulee** [jjxliu306/ng-form-element#11]
This dependency was not found:

* Vue in ./node_modules/ng-form-element/lib/ng-form-element.umd.min.js

To install it, you can run: npm install --save Vue

**Comment by wzqupup** [comment]
问题解决了吗，我也遇到了

**Comment by Cynric-h-new** [comment]
me too

**Comment by jjxliu306** [comment]
此问题已经处理，升级到2.0.4
