### ISSUE TITLE
动态表单中如果加入了多选框然后在预览里面选多选框的时候 会默认全选

### ISSUE THREAD

**Issue by jie123js** [jjxliu306/ng-form-element#12]
![image](https://github.com/jjxliu306/ng-form-element/assets/70522802/0d585342-7fe2-4604-bc42-dab0400c6e70)

**Comment by jjxliu306** [comment]
以确定可以重现，下个版本修复



在 2023-06-07 18:03:49，"郑杰" ***@***.***> 写道：

**Comment by jjxliu306** [comment]
2.0.5版本修复这个问题
