### ISSUE TITLE
图片上传组件设置了最大上传数量，达到上传数量后，上传按钮能否隐藏？

### ISSUE THREAD

**Issue by fulinkapp** [jjxliu306/ng-form-element#13]
RT.
比如我设置为2，然后上传了2张图片后，能否不显示上传按钮，
只有删除了一张后，才继续显示按钮。

**Comment by jjxliu306** [comment]
我在下个版本加上



在 2023-08-15 11:06:16，"fulinkapp" ***@***.***> 写道：

RT.
比如我设置为2，然后上传了2张图片后，能否不显示上传按钮，
只有删除了一张后，才继续显示按钮。

**Comment by jjxliu306** [comment]
再2.0.11+ 版本后会有这个配置
