### ISSUE TITLE
设计表单时，复制组件，没有改变key

### ISSUE THREAD

**Issue by fulinkapp** [jjxliu306/ng-form-element#14]
如图。
外面套了一层栅格布局组件。对栅格布局组件进行复制，里面的具体的组件没有改变key。
表现在表单设计时：选中一个组件，另外一个也会高亮

![image](https://github.com/jjxliu306/ng-form-element/assets/1005748/092bad67-1b11-409c-b657-87daeb38398c)

**Comment by fulinkapp** [comment]
同时发现栅格布局组件 里的 具体组件 无法 复制和删除

**Comment by jjxliu306** [comment]
此问题已经可以复现，本周会处理并发布一个新版本



在 2023-08-22 17:14:25，"fulinkapp" ***@***.***> 写道：

同时发现栅格布局组件 里的 具体组件 无法 复制和删除

**Comment by jjxliu306** [comment]
你这个我重现不出来，能不能说一下你具体如何重现



在 2023-08-22 17:01:07，"fulinkapp" ***@***.***> 写道：

如图。使用复制功能，保存后发现 key相同 ，表现在表单设计时：选中一个组件，另外一个也会高亮

**Comment by fulinkapp** [comment]
![ng-form](https://github.com/jjxliu306/ng-form-element/assets/1005748/8b3badfc-b4ee-4420-a1da-e0136a4a5633)
见这个gif，最后 我只点击选中了第四个输入框，但是第二个输入框也高亮了。因为他们的key是相同的，没有重新生成。

**Comment by jjxliu306** [comment]
会在2.0.11+ 和2.1.1+ 版本发布这个问题的处理



在 2023-08-25 13:45:35，"fulinkapp" ***@***.***> 写道：


见这个gif，最后 我只点击选中了第四个输入框，但是第二个输入框也高亮了。因为他们的key是相同的，没有重新生成。
