### ISSUE TITLE
级联选择器cascader的数据源选择api接口，没有children属性配置项

### ISSUE THREAD

**Issue by fulinkapp** [jjxliu306/ng-form-element#15]
RT.
看源码有 读取配置项 ：this.itemProp.children = this.record.options.remoteChildren

但表单设计时没提供这个配置项：remoteChildren

**Comment by jjxliu306** [comment]
已处理，此问题的修复版本将会在2.0.11+ 和2.1.1+ 版本发布



在 2023-08-26 09:19:58，"fulinkapp" ***@***.***> 写道：

RT.
看源码有 读取配置项 ：this.itemProp.children = this.record.options.remoteChildren

但表单设计时没提供这个配置项：remoteChildren
