### ISSUE TITLE
下拉联动配置问题

### ISSUE THREAD

**Issue by fulinkapp** [jjxliu306/ng-form-element#16]
![image](https://github.com/jjxliu306/ng-form-element/assets/1005748/9312e072-ef81-4eac-a000-00a42a2f6f71)
如图，
【省】字段 我配置的 数据源是 【API接口】，【市】字段 我配置的 数据源也是 【API接口】(/api/common/regions)，同时给【市】字段 配置了 联动，即：期望【省】 下拉选择改变时，【市】会调用接口：/api/common/regions?region_code=省字段值。
遇到问题：
1：用该表单新增数据时，还没有选择【省】，【市】立刻调用接口了(没有传region_code=省字段值)，能否【省】有值时【市】才调用接口？
2：对新增的数据(即：已保存到数据库的数据)进行编辑，【市】也立刻调用接口了，同样没有传 region_code=省字段值，导致下拉框里显示 市的编码，没有 显示 市的名称，见下图：
![image](https://github.com/jjxliu306/ng-form-element/assets/1005748/e98b8159-2f16-46d6-b448-c93a03de601f)

**Comment by jjxliu306** [comment]
你这个需求感觉应该使用自定义组件来实现。 默认多个组件联动时，只是再对数据切换后产生联动效果

**Comment by fulinkapp** [comment]
现在主要问题是： 编辑时回显不了，就是上面的第二个问题。

**Comment by jjxliu306** [comment]
已处理你这个需求了。升级2.1.3+ 或者2.0.12+
