### ISSUE TITLE
基础组件拖入布局组件时，数据字段 会重新生成，导致每次都要重新输入一遍

### ISSUE THREAD

**Issue by fulinkapp** [jjxliu306/ng-form-element#17]
布局组件拖出到外面，以及布局组件里拖动也一样会重新生成。
如图：
![ng-form-bug2](https://github.com/jjxliu306/ng-form-element/assets/1005748/ccfbe09a-ed1e-4a63-90dc-67cc7fd3d0d7)

**Comment by fulinkapp** [comment]
希望能保留原先命名的 数据字段 名称

**Comment by jjxliu306** [comment]
已处理。升级版本到2.1.3+ 或者 2.0.12+
