### ISSUE TITLE
怎么能动态的切换标签label名

### ISSUE THREAD

**Issue by ZhouJing0** [jjxliu306/ng-form-element#33]
太牛了 这个 这是我目前发现最厉害最能能用到项目的form。hhhh  就和动态显示一样 比如我一个开关，一个input  在开关打开的时候input的label 叫xxxx 在开关关闭的时候label 叫yyyy

**Comment by ZhouJing0** [comment]
还有动态验证 比如我一个开关，一个input， 在开关打开的时候input 必填 关闭时 不必填

**Comment by jjxliu306** [comment]
这个功能是有的，效验那块使用表达式效验即可



在 2024-01-23 10:49:44，"ZhouJing0" ***@***.***> 写道：

还有动态验证 比如我一个开关，一个input， 在开关打开的时候input 必填 关闭时 不必填
